### PR TITLE
PR for issue/283

### LINKED ISSUE #283: Dashboard, summary, correlation, MI and show on empty DF
Run the dashboard function on an empty data frame and receive:

```
java.lang.UnsupportedOperationException: empty.maxBy
    at scala.collection.TraversableOnce$class.maxBy(TraversableOnce.scala:223)
    at scala.collection.AbstractTraversable.maxBy(Traversable.scala:105)
    at de.frosner.dds.analytics.DateColumnStatisticsAggregator.topYear(DateColumnStatisticsAggregator.scala:62)
    at de.frosner.dds.core.SparkSqlFunctions$$anonfun$26.apply(SparkSqlFunctions.scala:280)
    at de.frosner.dds.core.SparkSqlFunctions$$anonfun$26.apply(SparkSqlFunctions.scala:262)
    at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:722)
    at scala.collection.mutable.ArraySeq.foreach(ArraySeq.scala:73)
    at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:721)
    at de.frosner.dds.core.SparkSqlFunctions$.createSummarize(SparkSqlFunctions.scala:262)
    at de.frosner.dds.core.SparkSqlFunctions$.createDashboard(SparkSqlFunctions.scala:350)
    at de.frosner.dds.core.DDS$.dashboard(DDS.scala:561)
    at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:213)
    at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:218)
    at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:220)
    at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:222)
    at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:224)
    at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:226)
    at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:228)
    at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:230)
    at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:232)
    at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:234)
    at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:236)
    at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:238)
    at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:240)
    at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:242)
    at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:244)
    at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:246)
    at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:248)
    at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:250)
    at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:252)
    at $iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:254)
    at $iwC$$iwC$$iwC$$iwC.<init>(<console>:256)
    at $iwC$$iwC$$iwC.<init>(<console>:258)
    at $iwC$$iwC.<init>(<console>:260)
    at $iwC.<init>(<console>:262)
    at <init>(<console>:264)
    at .<init>(<console>:268)
    at .<clinit>(<console>)
    at .<init>(<console>:7)
    at .<clinit>(<console>)
    at $print(<console>)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.apache.spark.repl.SparkIMain$ReadEvalPrint.call(SparkIMain.scala:1065)
    at org.apache.spark.repl.SparkIMain$Request.loadAndRun(SparkIMain.scala:1340)
    at org.apache.spark.repl.SparkIMain.loadAndRunReq$1(SparkIMain.scala:840)
    at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:871)
    at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:819)
    at org.apache.spark.repl.SparkILoop.reallyInterpret$1(SparkILoop.scala:857)
    at org.apache.spark.repl.SparkILoop.interpretStartingWith(SparkILoop.scala:902)
    at org.apache.spark.repl.SparkILoop.command(SparkILoop.scala:814)
    at org.apache.spark.repl.SparkILoop.processLine$1(SparkILoop.scala:657)
    at org.apache.spark.repl.SparkILoop.innerLoop$1(SparkILoop.scala:665)
    at org.apache.spark.repl.SparkILoop.org$apache$spark$repl$SparkILoop$$loop(SparkILoop.scala:670)
    at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply$mcZ$sp(SparkILoop.scala:997)
    at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply(SparkILoop.scala:945)
    at org.apache.spark.repl.SparkILoop$$anonfun$org$apache$spark$repl$SparkILoop$$process$1.apply(SparkILoop.scala:945)
    at scala.tools.nsc.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:135)
    at org.apache.spark.repl.SparkILoop.org$apache$spark$repl$SparkILoop$$process(SparkILoop.scala:945)
    at org.apache.spark.repl.SparkILoop.process(SparkILoop.scala:1059)
    at org.apache.spark.repl.Main$.main(Main.scala:31)
    at org.apache.spark.repl.Main.main(Main.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:672)
    at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
    at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

### PR DESCRIPTION
**Pull request by FRosner**
Fixes #283

### CODE REVIEW

File: core/src/main/scala/de/frosner/dds/analytics/CorrelationAggregator.scala [hunk 1]
```diff
@@ -6,6 +6,9 @@ class CorrelationAggregator(val numColumns: Int) extends Serializable {
 
   require(numColumns > 0, "You need to pass a positive number of columns to use the aggregator.")
 
+  def isEmpty: Boolean = !iteratedOnce
+  private[this] var iteratedOnce = false
```
Comment (FRosner) [inline core/src/main/scala/de/frosner/dds/analytics/CorrelationAggregator.scala]: Codacy Issue found: [Avoid mutable fields](https://www.codacy.com/app/frank_7/spawncamping-dds/file/2315269577/issues/source?bid=3046234&fileBranchId=3202429#l10)

File: core/src/test/scala/de/frosner/dds/core/DDSTest.scala [hunk 2]
```diff
@@ -34,6 +37,7 @@ class DDSTest extends FlatSpec with Matchers with MockFactory with BeforeAndAfte
     new SparkContext(conf)
   }
   private val sql: SQLContext = new SQLContext(sc)
+  import sql.implicits._
```
Comment (FRosner) [inline core/src/test/scala/de/frosner/dds/core/DDSTest.scala]: Codacy Issue found: [Put imports in the beginning of the package](https://www.codacy.com/app/frank_7/spawncamping-dds/file/2315269598/issues/source?bid=3046234&fileBranchId=3202429#l40)

File: core/src/main/scala/de/frosner/dds/analytics/ColumnsStatisticsAggregator.scala [hunk 3]
```diff
@@ -7,6 +7,14 @@ import scala.collection.mutable
 
 case class ColumnsStatisticsAggregator(schema: StructType) extends Serializable {
 
+  def totalCount = {
+    // This assumes that all aggregators have the same count (which should be the case)
+    val allAggregators = numericAggregators.map{ case (idx, (agg, field)) => agg } ++
+      dateAggregators.map{ case (idx, (agg, field)) => agg } ++
+      nominalAggregators.map{ case (idx, (agg, field)) => agg }
+    allAggregators.headOption.map(_.asInstanceOf[{ def totalCount: Long }].totalCount).getOrElse(0L)
```
Comment (FRosner) [inline core/src/main/scala/de/frosner/dds/analytics/ColumnsStatisticsAggregator.scala]: Codacy Issue found: [Avoid using structural types](https://www.codacy.com/app/frank_7/spawncamping-dds/file/2315269576/issues/source?bid=3046234&fileBranchId=3202429#l15)

Comment (FRosner) [inline core/src/main/scala/de/frosner/dds/analytics/ColumnsStatisticsAggregator.scala]: Codacy Issue found: [Avoid using structural types](https://www.codacy.com/app/frank_7/spawncamping-dds/file/2315269576/issues/source?bid=3046234&fileBranchId=3202429#l15)

File: core/src/main/scala/de/frosner/dds/analytics/MutualInformationAggregator.scala [hunk 4]
```diff
@@ -17,8 +17,12 @@ class MutualInformationAggregator(val numColumns: Int) extends Serializable {
     pXY
   }
 
+  def isEmpty: Boolean = !iteratedOnce
+  private[this] var iteratedOnce = false
```
Comment (FRosner) [inline core/src/main/scala/de/frosner/dds/analytics/MutualInformationAggregator.scala]: Codacy Issue found: [Avoid mutable fields](https://www.codacy.com/app/frank_7/spawncamping-dds/file/2315269579/issues/source?bid=3046234&fileBranchId=3202429#l21)

File: core/src/main/scala/de/frosner/dds/analytics/CorrelationAggregator.scala (hunk 1 above)
Comment (FRosner) [inline core/src/main/scala/de/frosner/dds/analytics/CorrelationAggregator.scala:10]: Codacy Issue found: [Avoid mutable fields](https://www.codacy.com/app/frank_7/spawncamping-dds/file/2315269577/issues/source?bid=3046234&fileBranchId=3202429#l10)

File: core/src/test/scala/de/frosner/dds/core/DDSTest.scala (hunk 2 above)
Comment (FRosner) [inline core/src/test/scala/de/frosner/dds/core/DDSTest.scala:40]: Codacy Issue found: [Put imports in the beginning of the package](https://www.codacy.com/app/frank_7/spawncamping-dds/file/2315269598/issues/source?bid=3046234&fileBranchId=3202429#l40)

File: core/src/main/scala/de/frosner/dds/analytics/ColumnsStatisticsAggregator.scala (hunk 3 above)
Comment (FRosner) [inline core/src/main/scala/de/frosner/dds/analytics/ColumnsStatisticsAggregator.scala:15]: Codacy Issue found: [Avoid using structural types](https://www.codacy.com/app/frank_7/spawncamping-dds/file/2315269576/issues/source?bid=3046234&fileBranchId=3202429#l15)

Comment (FRosner) [inline core/src/main/scala/de/frosner/dds/analytics/ColumnsStatisticsAggregator.scala:15]: Codacy Issue found: [Avoid using structural types](https://www.codacy.com/app/frank_7/spawncamping-dds/file/2315269576/issues/source?bid=3046234&fileBranchId=3202429#l15)

File: core/src/main/scala/de/frosner/dds/analytics/MutualInformationAggregator.scala (hunk 4 above)
Comment (FRosner) [inline core/src/main/scala/de/frosner/dds/analytics/MutualInformationAggregator.scala:21]: Codacy Issue found: [Avoid mutable fields](https://www.codacy.com/app/frank_7/spawncamping-dds/file/2315269579/issues/source?bid=3046234&fileBranchId=3202429#l21)
